/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.pkg1;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;


/**
 *
 * @author ektasharma
 */
public class BillGeneratorGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesGUI
     */
    public BillGeneratorGUI() {
        initComponents();
    }

    Bill bill = new Bill();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productCodeLbl = new javax.swing.JLabel();
        productQtyLbl = new javax.swing.JLabel();
        productCodeTxtField = new javax.swing.JTextField();
        productQtyTxtField = new javax.swing.JTextField();
        buyProductBtn = new javax.swing.JButton();
        saveBillBtn = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillSaleInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productCodeLbl.setText("Product Code");

        productQtyLbl.setText("Quantity");

        productCodeTxtField.setText("CodeTextField");
        productCodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCodeTxtFieldActionPerformed(evt);
            }
        });

        productQtyTxtField.setText("QuantityTextField");
        productQtyTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQtyTxtFieldActionPerformed(evt);
            }
        });

        buyProductBtn.setText("Buy");
        buyProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyProductBtnActionPerformed(evt);
            }
        });

        saveBillBtn.setText("Save");
        saveBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBillBtnActionPerformed(evt);
            }
        });

        errorMsg.setText("jLabel1");

        BillSaleInfo.setColumns(20);
        BillSaleInfo.setRows(5);
        jScrollPane1.setViewportView(BillSaleInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productCodeLbl)
                    .addComponent(buyProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productQtyLbl))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productQtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCodeLbl)
                    .addComponent(productCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productQtyLbl)
                            .addComponent(productQtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyProductBtn)
                    .addComponent(saveBillBtn))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param Event occurs when user click on buy button.
     */
    private void buyProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyProductBtnActionPerformed
        String productCode = productCodeTxtField.getText();
        int quantity = Integer.parseInt(productQtyTxtField.getText());

        ProductDB pDB = new ProductDB();
        Product product = null;
        try {
            product = pDB.productExists(productCode);

            if (product == null) {
                errorMsg.setText("Product not found");
            } else {
                product.setQuantity(quantity);
                bill.addProduct(product);
                errorMsg.setText("Product Bought");
            }
        } catch (Exception ex) {
            errorMsg.setText(ex.getMessage());
        }

    }//GEN-LAST:event_buyProductBtnActionPerformed

    /**
     * 
     * @param Event occurs when user click on save button. 
     */
    
    private void saveBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBillBtnActionPerformed
        String fileName = "billSaleFile.txt";
        File file = new File(fileName);

        try {
            ArrayList<Product> productList = bill.getProducts();
            ProductDB pDB = new ProductDB();
        
            java.io.PrintWriter output = new java.io.PrintWriter(new FileWriter((file)));
            output.println("Bill #: " + bill.getBillNumber());
            output.println("Date: " + bill.getDateOfSale());
            
            BillSaleInfo.setText("");
            BillSaleInfo.append("Bill #: " + bill.getBillNumber() + "\n");
            BillSaleInfo.append("Date: " + bill.getDateOfSale() + "\n");
            
            for (Product product : productList) {
                output.println(product.toString());
                BillSaleInfo.append(product.toString() + "\n");

            }

            output.println("Subtotal: " + bill.calSubTotalAmount());
            output.println("Taxes @ 13%: " + bill.calSubTotalAmount() * 0.13);
            output.println("Total: " + bill.amountAfterAddingTax());
            
            BillSaleInfo.append("Subtotal: " + bill.calSubTotalAmount() + "\n");
            BillSaleInfo.append("Taxes @ 13%: " + bill.calSubTotalAmount() * 0.13 + "\n");
            BillSaleInfo.append("Total: " + bill.amountAfterAddingTax() + "\n");

            output.close();
            errorMsg.setText("Bill Generated in File");

        } catch (Exception ex) {
             errorMsg.setText(ex.getMessage());
        }
    }//GEN-LAST:event_saveBillBtnActionPerformed

    private void productCodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCodeTxtFieldActionPerformed

    private void productQtyTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQtyTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQtyTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGeneratorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillSaleInfo;
    private javax.swing.JButton buyProductBtn;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel productCodeLbl;
    private javax.swing.JTextField productCodeTxtField;
    private javax.swing.JLabel productQtyLbl;
    private javax.swing.JTextField productQtyTxtField;
    private javax.swing.JButton saveBillBtn;
    // End of variables declaration//GEN-END:variables
}
